Try fixing deployment issue due to Git submodule issue
GH workflow error is:

	Fetching submodules
	  /usr/bin/git submodule sync --recursive
	  /usr/bin/git -c protocol.version=2 submodule update --init --force --recursive
	  Error: fatal: No url found for submodule path 'themes/apollo' in .gitmodules
	  Error: The process '/usr/bin/git' failed with exit code 128

See https://github.com/nicokosi/blog/actions/runs/20477519704/job/58844794672